language: php

dist: trusty

os: linux

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly
  - hhvm

cache:
  directories:
    - vendor/

install:
  - composer install
  - php ./bin/quest make:templates

env:
  - RIOTQUEST_LOAD_ENV=true
  - RIOTQUEST_STANDARD_LIMIT=3000:60
  - secure: "KZLcbMXR8GjUmEf0JrJweeY01ZbdTkI12hH1JMahjfihW4Ys5hnbJ9b8MAGohNFMpypFyiv6dVaoPpcv1riIUgMHF7s0jMUGwtC4E56cEKVz2Toch5nThw6S2VCBxRme9MnKLkzmqF5aodJIkcAc/gwmyFAoDb/PmNQaRYHGtPrXQxJKQTNESEje8WyR20nq08TD2wR7dr4EsBfXVvscQg98QYNSGX3WMHQ9ytiZtJfwSYYLM67NI6taP8e/p7OrK+T9zHpNIeJRNijnajybGkvPBNkN41aHUTE3qb1VcGOOFLwbCA32o0Ey19I0NggCiVgTOAL6rg6J/FSMlu3n6YCEjkRTG5jlb9+6dv+SSaJ7DEBnkYmapQulxJQ7QavvHwXWXAM4TDwfRQI1FVhSEnegAtsUEZy+eWmxBJ0alq5i8tV5xrbEhgKt+gDPPoXLvDjMaqifWLKq09/g/OIyC8RWcXbHHBMQCsAeIowltLzSVcJzBER+TT/kFMNdrKd3JUaThn2reIJ0W/y3ZQ1UdLqg8uHdyf3F/lsk5LESWFqLid3k/hf9IveRgQ/5Hz+2ZV9WA399FzYC+OPG13+2SLVe4+MnlAQpBNCJE/qdW6n54gXDIbwOs5AVQ0KdxDwx4YPJNHH9y9mA2eWClE+Af6J7asYfVDfEsKRljtLJl8Y="

script:
  - vendor/bin/phpunit
